M5Unified port
chhorisberger/M5StackMenuSystem pull request #3
Opened 2024-04-25 22:46 UTC by lvlhead

I have been porting this library over to the M5Unified library instead of M5Stack in order to support a project I am working on.  At the moment it runs on an `M5Stack Core2 v1.1` with one issue in detecting the width/height inside of Layout.cpp.  This can be resolved by customizing the menu in the user code.

Please let me know if there are any issues with this approach.  Thanks!

```
Menu mainMenu("Main Menu");
customizeLayout(mainMenu.getLayout());
void customizeLayout(Layout& layout) {
    layout.SCREEN_WIDTH = M5.Display.width();
    layout.SCREEN_HEIGHT = M5.Display.height();
}
```

2024-04-26 16:29 UTC, lvlhead commented
@chhorisberger Hope you've had a good week. Pinging you in this pull request :)

2024-04-28 10:11 UTC, chhorisberger commented
@lvlhead Thanks for contributing! I'll check/test your proposed changes and will get back to you ASAP

2024-04-28 11:56 UTC, chhorisberger requested changes

2024-04-28 15:12 UTC, chhorisberger approved these changes

2024-04-28 15:12 UTC, merged

2024-04-28 15:13 UTC, chhorisberger commented on src/CallbackMenuItem.cpp
Update: On a second though, I'll just replace those myself after merging your pull request ;)

2024-04-28 15:33 UTC, chhorisberger commented
Also, I found a fix for the issue you mentioned about screen width and height.
The point is that after the switch to M5Unified, the width and height can only be determined at runtime.
The solution was to create an "init" method and get/set them there

2024-04-28 15:46 UTC, chhorisberger commented
Release is done. Just a matter of waiting a few hours, until the ardunio library registry picks them

https://downloads.arduino.cc/libraries/logs/github.com/chhorisberger/M5StackMenuSystem/

2024-04-28 19:34 UTC, mdxs commented
Excellent, thanks for working on this. Great idea to port it to M5Unified!
I hope to get around to testing this implementation later this week.

2024-04-29 19:10 UTC, chhorisberger commented
Version 1.2.0 now available in Arduino IDE

2024-04-29 19:17 UTC, lvlhead commented
@chhorisberger Thank you for an amazing library!